config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "foods#index"
  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    resources :ingredients, only: [:new, :create, :destroy]
  end
  resources :foods, only: [:new, :create, :destroy]
  resources :shopping_list, only: [:index]
  resources :public_recipes, only: [:index]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Recipe, public: true

    return unless user.present?

    can :manage, Food, user_id: user.id
    can :manage, Recipe, user_id: user.id
    can :manage, RecipeFood, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods
  validates :name, :measurement_unit, :price, :quantity, presence: true
  validates :price, :quantity, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, numericality: { only_integer: true }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods
  validates :name, :preparation_time, :cooking_time, :description, presence: true
  validates :preparation_time, :cooking_time, numericality: { greater_than_or_equal_to: 0 }
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
  validates :quantity, presence: true
  validates :quantity, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable # , :confirmable
  has_many :foods, dependent: :destroy
  has_many :recipes, dependent: :destroy
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  def index
    @foods = Food.includes(:user).where(users: { id: current_user.id })
    puts
  end

  def new
    @food = Food.new
  end

  def create
    puts current_user.id
    @food = Food.new(
      name: food_params[:name],
      measurement_unit: food_params[:measurement_unit],
      price: food_params[:price],
      quantity: food_params[:quantity],
      user_id: current_user.id
    )

    if @food.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy

    flash[:notice] = 'Food deleted successfully'
    redirect_back(fallback_location: root_path)
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def new
    @recipe_food = RecipeFood.new
    @foods = current_user.foods.all
    @recipe = params[:recipe_id]
  end

  def create
    @food = current_user.foods.find(params[:recipe_food][:food_id])
    @recipe = current_user.recipes.find(params[:recipe_id])
    @quantity = params[:recipe_food][:quantity]

    @ingredient = RecipeFood.new(quantity: @quantity, recipe: @recipe, food: @food)

    if @ingredient.save
      redirect_to recipe_path(@recipe), notice: 'Ingredient added successfully'
    else
      flash.now[:alert] = 'Unable to add an igredient'
      render :new
    end
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @food = @recipe.foods.find(params[:food_id])
    @ingredient = RecipeFood.where(food_id: @food)
    @ingredient[0].destroy
    redirect_to recipe_path(@recipe), notice: 'Ingredient Successfully deleted'
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @public_recipes = Recipe.includes(:recipe_foods, :foods, :user).where(public: true)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!
  def index
    @recipes = current_user.recipes.all
  end

  def show
    @recipe = current_user.recipes.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)

    if @recipe.save
      redirect_to recipes_path, notice: 'Recipe created successfully'
    else
      flash.now[:alert] = 'Unable to create a recipe'
      render :new
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path, notice: 'Recipe successfully deleted'
  end

  private

  def recipe_params
    permitted_params = params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description)
    permitted_params[:public] = params[:recipe][:public] == '1'
    permitted_params
  end
end

app/controllers/shopping_list_controller.rb
class ShoppingListController < ApplicationController
  before_action :authenticate_user!
  def index
    @current_user = current_user
    @foods = []
    @total_price = 0
    flag = true

    current_user.recipes.includes([:foods]).each do |recipe|
      recipe.foods.each do |food|
        q = RecipeFood.find_by(food_id: food.id).quantity
        f = current_user.foods.find(food.id)
        next unless (f.quantity - q).negative? && flag

        @foods << {
          name: f.name,
          quantity: (q - f.quantity),
          price: f.price * (q - f.quantity)
        }
      end
    end
    @foods.each { |f| @total_price += f[:price] }
    @foods
  end

  def check_for_duplicate(foods, food, quantity)
    foods.each do |food_item|
      next unless food_item[:name] == food.name

      food_item[:quantity] = food_item[:quantity] - quantity
      food_item[:price] = food_item[:quantity] * food.price
      return false
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_list_helper.rb
module ShoppingListHelper
end

app/views/foods/index.html.erb
<div class="w-full">
  <div class="flex justify-between mb-3">
    <h1 class="text-3xl text-blue-600">Foods list</h1>
    <%= link_to 'Add Food', new_food_path(params[:user_id]), class: 'btn btn-success btn-sm' %>
  </div>
  <table class="table border w-full">
    <thead class="border ">
      <tr class="border text-2xl">
        <th class="border p-2">Food</th>
        <th class="border p-2">Measurement unit</th>
        <th class="border p-2">Unit price</th>
        <th class="border p-2">Quantity</th>
        <th class="border p-2">Actions</th>
      </tr>
    </thead>
    <tbody class="border ">
      <% @foods.each do |food| %>
        <tr class="border ">
          <td class="border   p-1"><%= food.name %></td>
          <td class="border  p-1"><%= food.measurement_unit %></td>
          <td class="border  p-1"><%= food.price %></td>
          <td class="border  p-1"><%=  food.quantity  %></td>
          <td class="border  p-1">
            <%= button_to 'Delete', food_path(food.id), method: :delete, class: 'btn btn-secondary btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/foods/new.html.erb
<div class="w-full  shadow-lg py-10">
  <h2 class='text-2xl text-center mb-5'>Create new Food</h2>
  <%= form_with(model: @food, url: foods_path) do |form| %>
    <div class='flex flex-col justify-center items-center gap-4'>
      <div class="flex flex-col">
        <%= form.label :name, 'Name: '%>
        <%= form.text_field :name, placeholder: "Food name", class: "input input-bordered input-primary w-full max-w-xs"  %>
      </div>
      <div class="flex flex-col">
          <%= form.label :measurement_unit, 'Measurement unit: '%>
          <%= form.select :measurement_unit, [["grams"], ["kilos"], ["liters"], ["milliliters"]], {}, class: "input input-bordered input-primary w-full max-w-xs" %>
      </div>
      <div class="flex flex-col">
        <%= form.label :price, 'Price: '%>
        <%= form.number_field :price, placeholder: "Price", class: "input input-bordered input-primary w-full max-w-xs" %>
      </div>
      <div class="flex flex-col">
        <%= form.label :name, 'Quantity: '%>
        <%= form.number_field :quantity, placeholder: "Quantity", class: "input input-bordered input-primary w-full max-w-xs" %>
      </div>
      <%= form.submit "Add New Food", class: "btn btn-primary " %>
  </div>
  <% end %>
</div>

app/views/ingredients/new.html.erb
<div class="w-full  shadow-lg py-10">
  <h2 class='text-2xl text-center mb-5'>Add an Ingredient</h2>
  <%= form_with(model: @recipe_food, url: recipe_ingredients_path) do |form| %>
    <div class='flex flex-col justify-center items-center gap-4'>
      <div class="field">
      <%= form.label :food_id, 'Ingredient: '%>
         <%= form.select :food_id, options_from_collection_for_select(@foods, :id, :name), { prompt: 'Select an Ingredient' }, class: "select select-bordered w-full max-w-xs" %>
      </div>
      <div class="field">
      <%= form.label :quantity, 'Quantity: '%>
        <%= form.number_field :quantity, class: "input input-bordered w-full max-w-xs " %>
      </div>
      <%= form.submit "Add ingredient", class: "btn btn-primary btn-sm" %>
  </div>
  <% end %>
   <div class="flex justify-center p-1">
    <%= link_to 'Cancle', recipe_path(@recipe), class: 'btn btn-secondary btn-sm'%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme='light'>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/daisyui@2.14.1/dist/full.css" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render '/shared/navbar'%>

    <p class="notice text-center text-green-600"><%= notice%></p>
    <p class="alert text-center text-yellow-600"><%= alert %></p>
    
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/public_recipes/index.html.erb
<div class="container w-full shadow-lg  p-5">
  <h1 class="text-4xl text-center">Public Recipes</h1>
  <ul class="w-full">
    <% @public_recipes.each do |recipe|%>
      <%= link_to recipe_path(recipe) do%>
        <li class ="flex px-5  border shadow-xl m-2 w-full">
          <div class="grid gap-3 w-1/2 my-2">
              <h3 class='text-3xl'><strong><%= recipe.name%></strong></h3>
              <span>By: <%= recipe.user.name%></span>
          </div><%=  %>
          <div class="grid gap-3 w-1/2 my-2">
            <span class="text-2xl">Total food items: <%= recipe.foods.count %></span>
            <span class="text-2xl">Total price: $<%= recipe.foods.sum(:price) %></span>
          </div>
        </li>
      <% end %><%=  %>
    <% end %>
  </ul>
</div>

app/views/recipes/index.html.erb
<div class="container w-full shadow-lg  p-5">
  <div class='flex justify-between'>
    <h1 class='text-4xl'>Add Recipe</h1>
    <%= link_to 'Add recipe', new_recipe_path, class: 'btn btn-success btn-sm '%>
  </div>
  <ul class="w-full ">
    <% @recipes.each do |recipe|%>
      <%= link_to recipe_path(recipe) do%>
        <li class ="flex px-5  border shadow-xl m-2 w-full">
          <div class="grid gap-3 w-1/2 my-2">
              <h3 class='text-3xl'><strong><%= recipe.name%></strong></h3>
              <%= button_to 'REMOVE', recipe_path(recipe), method: :delete, class: 'btn btn-secondary btn-sm', onclick: 'event.stopPropagation();' %>
          </div><%=  %>
          <p class="text-2xl"><%= recipe.description %></p>
        </li>
      <% end %><%=  %>
    <% end %>
  </ul>
</div>

app/views/recipes/new.html.erb
<div class="grid grid-col justify-center items-center w-full shadow-xl p-10">
  <h1 class='text-4xl text-center'>Add Recipe</h1>
  <%= form_with(model: @recipe, url: recipes_path, method: :post) do |form| %>
    <div class="flex flex-col">
      <%= form.label :name, class: "label-text"%>
      <%= form.text_field :name , class: 'input input-bordered input-primary w-full max-w-xs' %>
    </div>

    <div class="flex flex-col">
      <%= form.label :preparation_time %>
      <%= form.number_field :preparation_time, class: 'input input-bordered input-primary w-full max-w-xs' %>
    </div>

    <div class="flex flex-col">
      <%= form.label :cooking_time %>
      <%= form.number_field :cooking_time, class: 'input input-bordered input-primary w-full max-w-xs' %>
    </div>

    <div class="flex flex-col">
      <%= form.label :description %>
      <%= form.text_area :description, class: 'input input-bordered input-primary w-full max-w-xs' %>
    </div>

    <div class=" label cursor-pointer">
      <%= form.check_box :public, class: 'checkbox checkbox-primary' %>
      <%= form.label :public, class: 'label-text' %>
    </div>

    <div class="actions ">
      <%= form.submit "Create Recipe", class: 'btn btn-primary w-full' %>
    </div>
  <% end %>
</div>

app/views/recipes/show.html.erb
<div class='w-full flex flex-col gap-4'>
  <h2 class="text-4xl text-center"><%= @recipe.name%></h2>
  <div class="flex justify-between">
    <p class="text-2xl">Preparation time: <%= @recipe.preparation_time%> hour</p>
    <div class="flex items-center gap-3">
      <p class="text-2xl">Public</p>
         <input type="checkbox" id="checkbox" class="checkbox checkbox-primary" <%= @recipe.public? ? 'checked' : '' %> />
    </div>
  </div>
  <p class="text-2xl">Cooking time: <%= @recipe.cooking_time%> hour</p>
  <p class="text-2xl">Steps go here...</p>
  <div class="flex justify-between">
    <%= link_to 'Generate shopping list', '#', class: 'btn btn-success btn-sm'%>
    <%= link_to 'Add ingredient', new_recipe_ingredient_path(@recipe), class: 'btn btn-success btn-sm'%>
  </div>
  <table class="table border w-full">
    <thead class="border border-black">
      <tr class="border text-2xl">
        <th class="border p-2">Food</th>
        <th class="border p-2">Quantity</th>
        <th class="border p-2">Value</th>
        <th class="border p-2">Actions</th>
      </tr>
    </thead>
    <tbody class="border border-black">
      <% @recipe.foods.each do |food| %>
        <tr class="border border-black">
          <td class="border  border-black p-1"><%= food.name %></td>
          <%@quantity = RecipeFood.find_by(food_id: food.id).quantity%>
          <td class="border border-black p-1"><%= @quantity %> <%= food.measurement_unit%></td>
          <td class="border border-black p-1">$<%= food.price %></td>
          <td class="border border-black p-1">
            <%= button_to 'Delete', recipe_ingredient_path(recipe_id: @recipe,food_id: food), method: :delete, class: 'btn btn-secondary btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="flex justify-center">
    <%= link_to 'Back to recipes page', recipes_path, class: 'btn btn-primary btn-sm'%>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar bg-base-100 shadow-2xl">
  <div class="navbar-start">
        <%= link_to 'Recipe APP', root_path,  class: "btn btn-ghost normal-case text-4l"%>
  </div>
  <div class="navbar-center hidden lg:flex">
    <ul class="menu menu-horizontal px-1">
      <li>
        <%= link_to 'Food List', root_path, class: 'link link-primary'%>
      </li>
      <li>
        <%= link_to 'Public Recipes', public_recipes_path, class: 'link link-primary'%>
      </li>
      <li>
        <%= link_to 'Recipe List', recipes_path,  class: 'link link-primary' %>
      </li>
      <li>
        <%= link_to 'Shopping List', shopping_list_index_path,  class: 'link link-primary' %>
      </li>
   
    </ul>
  </div>
  <div class="navbar-end">
    <% if user_signed_in? %>
        <%= button_to "Logout", destroy_user_session_path, method: :delete, class: 'btn btn-sm btn-secondary' %>
    <% end %>
  </div>
</div>

app/views/shopping_list/index.html.erb
<div class="grid grid-col w-full">
  <h1 class='text-5xl text-center'>Shopping List</h1>
  <div class="flex justify-between">
    <div class="text-2xl">Amount of food items to buy: <span class="text-3xl"> <%= @foods.length%> </span></div>
    <div class="text-2xl">Total value of food needed: <span class="text-3xl">$ <%= @total_price %> </span></div>
  </div>

  <div>
    <% if @foods.length.zero? %>
      <h2 class="text-center text-xl bg-green-900 text-white">All ingredients are set to make the recipe!</h2>
    <% else %>
      <table class="table border w-full">
        <thead class="border">
          <tr class="border text-2xl">
            <th class="border p-2">Food</th>
            <th class="border p-2">Quantity</th>
            <th class="border p-2">Total price</th>
          </tr>
        </thead>
        <tbody class="border">
          <% @foods.each do |food| %>
            <tr class="border">
              <td class="border  p-1"><%= food[:name] %></td>
              <td class="border p-1"><%= food[:quantity] %></td>
              <td class="border p-1">$<%= food[:price]   %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>